import Head from 'next/head'

export const getStaticPaths = async () => {
    const res = await fetch('https://jsonplaceholder.typicode.com/users');
    const data = await res.json();
  
    // map data to an array of path objects with params (id)
    const paths = data.map(ninja => {
      return {
        params: { id: ninja.id.toString() }
      }
    })
  
    return {
      paths,
      fallback: false
    }
  }
  


  export const getStaticProps = async (context) => {
        const id = context.params.id;
        const res = await fetch('https://jsonplaceholder.typicode.com/users/' + id);
        const data = await res.json();

    return {
        props: { ninja: data }
    }
}


function Details({ ninja }) {
  return (
    <>
        <Head>
        <title>Ninja List | Ninja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="ninjas, ninja list, ninja-list" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1>{ ninja.name }</h1>
        <p>{ ninja.email }</p>
        <p>{ ninja.website }</p>
        <p>{ ninja.address.city }</p>
    </>
  )
}

export default Details

