import Head from 'next/head'

function about() {
  return (
    <>
        <Head>
        <title>Ninja List | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="ninjas, ninja list, ninja-list" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique velit saepe excepturi! Impedit repudiandae minima aliquam voluptates non molestiae cum ut quas recusandae soluta quae, sapiente reprehenderit consequuntur illum. Laboriosam.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique velit saepe excepturi! Impedit repudiandae minima aliquam voluptates non molestiae cum ut quas recusandae soluta quae, sapiente reprehenderit consequuntur illum. Laboriosam.</p>
    </>
  )
}

export default about
