import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ninja List | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="ninjas, ninja list, ninja-list" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
        <h1 className={styles.title}>Home Page</h1>
        <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus iste debitis nihil voluptatum ab ut ratione laudantium, doloremque modi eaque, quisquam architecto nisi natus autem tempore hic! Maxime, sapiente omnis.</p>
        <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus iste debitis nihil voluptatum ab ut ratione laudantium, doloremque modi eaque, quisquam architecto nisi natus autem tempore hic! Maxime, sapiente omnis.</p>
      <Link href="/ninjas">
        <a className={styles.btn}>See Ninja Listing</a>
      </Link>
    </>
  )
}
  